### ISSUE TITLE
`Range::join_cover` is unsound 💥

### ISSUE THREAD

**Issue by CAD97** [bluss/indexing#12]
```rust
let array = [0, 1, 2, 3, 4, 5];
let ix = scope(&array[..], |arr| {
    let left = arr.vet_range(0..2).unwrap();
    let left = left.nonempty().unwrap();
    let (_, right) = arr.range().frontiers();

    let joined = right.join_cover(left);
    let ix = joined.first();
    dbg!(ix);
    dbg!(arr[ix]);
    ix.integer()
});
dbg!(array[ix]);
```

```
[src\main.rs:12] ix = Index(6)
[src\main.rs:13] arr[ix] = 9699328
thread 'main' panicked at 'index out of bounds: the len is 6 but the index is 6', src\main.rs:16:10
stack backtrace:
   0: std::sys_common::backtrace::_print
             at src\libstd\sys\windows\backtrace/mod.rs:95
             at src\libstd\sys\windows\backtrace/mod.rs:82
             at src\libstd\sys_common/backtrace.rs:71
   1: std::panicking::default_hook::{{closure}}
             at src\libstd\sys_common/backtrace.rs:59
             at src\libstd/panicking.rs:197
   2: std::panicking::default_hook
             at src\libstd/panicking.rs:211
   3: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:474
   4: std::panicking::continue_panic_fmt
             at src\libstd/panicking.rs:381
   5: rust_begin_unwind
             at src\libstd/panicking.rs:308
   6: core::panicking::panic_fmt
             at src\libcore/panicking.rs:85
   7: core::panicking::panic_bounds_check
             at src\libcore/panicking.rs:61
   8: playground::main
             at src/main.rs:16
   9: std::rt::lang_start::{{closure}}
             at /rustc/2bafaaf66556ba153fddb00def6d205abb5beff2\src\libstd/rt.rs:64
  10: std::panicking::try::do_call
             at src\libstd/rt.rs:49
             at src\libstd/panicking.rs:293
  11: _rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:87
  12: std::rt::lang_start_internal
             at src\libstd/panicking.rs:272
             at src\libstd/panic.rs:388
             at src\libstd/rt.rs:48
  13: std::rt::lang_start
             at /rustc/2bafaaf66556ba153fddb00def6d205abb5beff2\src\libstd/rt.rs:64
  14: main
  15: _tmainCRTStartup
  16: mainCRTStartup
  17: unit_addrs_search
  18: unit_addrs_search
error: process didn't exit successfully: `target\debug\playground.exe` (exit code: 101)
```

The problem is `-> Range<'id, <(P, Q) as ProofAdd>::Sum>`: if `self` is `Unknown`, `other` is `NonEmpty`, and `other.end()` < `self.end()`, `self.join_cover(other)` will return `self` unchanged, but with the `NonEmpty` proof. This method should instead be `-> Range<'id, P>`, as the returned range may not cover the argument range if it is strictly less than the self range.

Shameless plug: I've been working on a fork of this crate, [indexing-str](https://crates.io/crates/indexing-str), which adds string slice support, which is the reason for my finding this and #11. I'm happy to upstream my improvements once I've finished the 0.2 improvements, as it I believe brings indexing's unsafe up to modern expectations and loses no power (once the 0.2 version is finished, anyway).

**Comment by CAD97** [comment]
This seems to be NLL's "fault": `mixup2.rs` compiles fine with `edition=2018` but errors with `edition=2015`.

**Comment by bluss** [comment]
Nice. Of course it should be fixed.
That said, indexing is already up to its expectations on itself since its documentation says *This is an experiment. The API is all of inconsistent, incomplete and redundant, but it explores interesting concepts.*

A lot of it is quick-hack quality.
